# Generated by Django 2.0.4 on 2018-04-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('intro', models.TextField(verbose_name='intro')),
                ('post_url', models.URLField(verbose_name='post_url')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('author_url', models.URLField(verbose_name='author_url')),
                ('date', models.CharField(max_length=100, verbose_name='date')),
            ],
        ),
    ]
